version: '3.8'

services:
  bot:
    build: ./bot/
    volumes:
      - ./bot/bot:/bot/bot
    ports:
      - 80:80
    depends_on:
      - db
    env_file:
      - config.env
  
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data/
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    env_file:
      - config.env

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - config.env
    ports:
      - "5050:80"
    links:
      - "db:pgsql-server"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/config/:/etc/prometheus/
      - ./prometheus/prometheus_data:/prometheus
    ports:
     - 9090:9090