{
 "title": "Bot_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total number of commands",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "commands_total", "legendFormat": "Total number of commands" }
   ]
  },
  {
   "title": "Canceled commands",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "commands_canceld_total",
     "legendFormat": "Total number of canceled countdowns"
    }
   ]
  },
  {
   "title": "Invalid start countdown commands",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "error_starts_total",
     "legendFormat": "Invalid start countdown commands"
    }
   ]
  },
  {
   "title": "Invalid stop countdown commands",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "error_stops_total",
     "legendFormat": "Invalid stop countdown commands"
    }
   ]
  },
  {
   "title": "Number of invalid commands",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "invalid_commands_total",
     "legendFormat": "Total number of invalid commands given"
    }
   ]
  }
 ]
}